version: '3.8'  # Указываем версию Docker Compose

services:
  device_lib:
    build:
      context: .  # Контекст сборки (где находится Dockerfile)
      dockerfile: Dockerfile  # Имя Dockerfile (по умолчанию Dockerfile)
    ports:
      - "8000:8000"  # Пробрасываем порт
    environment:
      - SECRET_KEY=my_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=postgresql+asyncpg://ilya:12345@db/mobile_app
      - DATABASE_URL_ALEMBIC=postgresql://ilya:12345@db/mobile_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app  # Связываем текущую директорию с /app в контейнере
    container_name: storage_api
    networks:
      - device_db_network
      
    restart: always  # Перезапуск контейнера в случае сбоя


networks:
  device_db_network:
    external: true